  - name: backport patches to 8.11 branch
    conditions:
      - merged
      - label=backport-v8.11.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.11"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
