---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-assetbeat
  description: Buildkite Pipeline for assetbeat
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/assetbeat

spec:
  type: buildkite-pipeline
  owner: group:observability-asset-management
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: assetbeat
    spec:
      repository: elastic/assetbeat
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        observability-asset-management:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
